// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/Kernel-Ghost-Exfil"
)

// loadCounter returns the embedded CollectionSpec for counter.
func loadCounter() (*Kernel-Ghost-Exfil.CollectionSpec, error) {
	reader := bytes.NewReader(_CounterBytes)
	spec, err := Kernel-Ghost-Exfil.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load counter: %w", err)
	}

	return spec, err
}

// loadCounterObjects loads counter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*counterObjects
//	*counterPrograms
//	*counterMaps
//
// See Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign documentation for details.
func loadCounterObjects(obj interface{}, opts *Kernel-Ghost-Exfil.CollectionOptions) error {
	spec, err := loadCounter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// counterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed Kernel-Ghost-Exfil.CollectionSpec.Assign.
type counterSpecs struct {
	counterProgramSpecs
	counterMapSpecs
	counterVariableSpecs
}

// counterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed Kernel-Ghost-Exfil.CollectionSpec.Assign.
type counterProgramSpecs struct {
	CountPackets *Kernel-Ghost-Exfil.ProgramSpec `Kernel-Ghost-Exfil:"count_packets"`
}

// counterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed Kernel-Ghost-Exfil.CollectionSpec.Assign.
type counterMapSpecs struct {
	PktCount *Kernel-Ghost-Exfil.MapSpec `Kernel-Ghost-Exfil:"pkt_count"`
}

// counterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed Kernel-Ghost-Exfil.CollectionSpec.Assign.
type counterVariableSpecs struct {
}

// counterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCounterObjects or Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign.
type counterObjects struct {
	counterPrograms
	counterMaps
	counterVariables
}

func (o *counterObjects) Close() error {
	return _CounterClose(
		&o.counterPrograms,
		&o.counterMaps,
	)
}

// counterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCounterObjects or Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign.
type counterMaps struct {
	PktCount *Kernel-Ghost-Exfil.Map `Kernel-Ghost-Exfil:"pkt_count"`
}

func (m *counterMaps) Close() error {
	return _CounterClose(
		m.PktCount,
	)
}

// counterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCounterObjects or Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign.
type counterVariables struct {
}

// counterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCounterObjects or Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign.
type counterPrograms struct {
	CountPackets *Kernel-Ghost-Exfil.Program `Kernel-Ghost-Exfil:"count_packets"`
}

func (p *counterPrograms) Close() error {
	return _CounterClose(
		p.CountPackets,
	)
}

func _CounterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed counter_bpfeb.o
var _CounterBytes []byte
