// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/Kernel-Ghost-Exfil"
)

type bpfEvent struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*Kernel-Ghost-Exfil.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := Kernel-Ghost-Exfil.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *Kernel-Ghost-Exfil.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed Kernel-Ghost-Exfil.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed Kernel-Ghost-Exfil.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeExecve *Kernel-Ghost-Exfil.ProgramSpec `Kernel-Ghost-Exfil:"kprobe_execve"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed Kernel-Ghost-Exfil.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events *Kernel-Ghost-Exfil.MapSpec `Kernel-Ghost-Exfil:"events"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed Kernel-Ghost-Exfil.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events *Kernel-Ghost-Exfil.Map `Kernel-Ghost-Exfil:"events"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or Kernel-Ghost-Exfil.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeExecve *Kernel-Ghost-Exfil.Program `Kernel-Ghost-Exfil:"kprobe_execve"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeExecve,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
